version: "3.7"
services:
    vue-cli:
        build: 
            context: .
            target: vue-cli
        volumes:
            - .:/app
        command: /usr/bin/true
    app:
        build: 
            context: .
            target: app
        volumes:
            - .:/app
    